adidas/api-guidelines

.github/CODE_OF_CONDUCT.md, .github/CONTRIBUTING.md, README.md
Update README to follow adidas GH guidelines.
=> Prepare for the team migration

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Add .github templates for issue and PRs, #8

rest-api-guidelines/miscellaneous.md
Add links to official headers list and rest/http apis standards
=> Add additional resources links

rest-api-guidelines/functionality/message/error-reporting.md
Adds details on parameters and extends on the best practices
=> Errors problem json

rest-api-guidelines/execution/asynchronous-tasks.md
Add example of asynchronous operation using HAL and problem detail
=> Asynchronous operations example

ruleset.md
A draft on the ruleset for OAS linters.
=> Add ruleset extracted from the guidelines

README.md
Fixes #
Howto on spectral and rulesets
=> Ruleset readme

README.md, acknowledgements.md, general-guidelines/validating-api-descriptions.md
Add a guide on how validate API specifications using spectral.
=> Spectral guide

.spectral.yml
Prefix all rules with 'adidas-' and add/move the oas version tag to just after the prefix.
=> Change naming convention for rules.

rest-api-guidelines/rest.md
=> Fix typos on introduction

rest-api-guidelines/core-principles/design-platform.md
Fixes #
Typo in Swagger project url
subj
=> Fix swagger.io url

yarn.lock
Old version had a security issue
Fixes #
-
-
-
=> Update auth0-js package dependency

examples/valid/demo-orderapi-v3.oas2.yaml
Fixes #
YAML keys should be strings rather than numbers
=> Change number values to strings

rest-api-guidelines/core-principles/design-platform.md
Fixes #
Removal of mention to automation in pipelines
=> Removed automation mention

rest-api-guidelines/guides/complete-api-development.md
=> Change step for design

rest-api-guidelines/guides/complete-api-development.md
=> repair broken links

README.md
=> Add working version

rest-api-guidelines/message/error-reporting.md
=> Typo Fixed

README.md
=> Update README.md - minor typos.

asynchronous-api-guidelines/kafka-asynchronous-guidelines/g_contact_information.md
Adding url field as a possible contact detail information
=> Update g_contact_information.md with url field
